# Config wiki and help can be found at https://gitlab.com/Zenya4/aurora/-/wikis/General-Configuration
# For internal reference only, do not change the config version
config-version: 2

# Only spawn particles in the given CHUNK radius around players
# It is highly recommended to keep this value at 2-3 for the best viewing experience
particle-spawn-radius: 3

# Whether or not ambient particles should only be displayed at night
# Set to false to always show particles regardless of time
night-only: false

# Aurora will be disabled in the following worlds. No ambient particles will be shown at all in these worlds.
# World names are cAsE sEnSiTiVe
disabled-worlds:
  - "vanilla"
  - "testworld"